### ISSUE TITLE
Nav case that does not collapse

### ISSUE THREAD

**Issue by hguthrie** [magento-devdocs/gatsby-doc-shell#4]
I am not sure this is really an issue. But if a Title in the left navigation does not contain a URL, but does contain sub-titles with or with our URLs, it will not collapse.

The reason this could be important is some people will use the Title as a "category" of topics, whereas it is not used as a topic itself. I don't use them that way, but I've seen it many times.

For example, the following section has a title "Git repositories" without a URL. 
```
  - title: Program management
    url: /program/web-ui-tour/
    pages:
      - title: Git repositories
        pages:
          - title: Test 1
          - title: Test 2
      - title: Environments
      - title: Pipelines
```

Even though Git repositories contains multiple sub-titles, I am not able to collapse it.

<img width="256" alt="Screen Shot 2020-05-29 at 16 20 19" src="https://user-images.githubusercontent.com/5817319/83306746-c5115500-a1c8-11ea-815b-a2ca59f70443.png">
<img width="262" alt="Screen Shot 2020-05-29 at 16 20 11" src="https://user-images.githubusercontent.com/5817319/83306753-c80c4580-a1c8-11ea-939e-c124d421e31e.png">

I am able to collapse "Program management" because it has a landing page (URL). But, if I remove the URL and choose to not provide a landing page for the Program management section, then it will not collapse.

If this is working as expected, no problem, but then we will need to provide some guidelines for that usage.
